name: streamy
version: 0.0.5
description: >
  An experimental client API generator for services described using Google's API
  discovery format (https://developers.google.com/discovery/v1/using#discovery-doc).
  The generator comes with templates that generate streaming API via dart:async's
  Stream object.
authors:
- Alex Rickabaugh <arick@google.com>
- Yegor Jbanov <yjbanov@google.com>
homepage: https://github.com/google/streamy-dart
environment:
  sdk: '>=0.8.7'
dependencies:
  mustache: ">=0.1.5"
  args: ">=0.8.7"
  meta: ">=0.8.7"
  fixnum: ">=0.8.7"
  json: ">=0.8.7"
  observe: ">=0.8.7"
  quiver: ">=0.12.0"
dev_dependencies:
  path: any
  unittest: any
  benchmark_harness: ">=0.8.7"
